/*
 * generated by Xtext 2.9.1
 */
package co.edu.javeriana.midas.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MidasProposalProvider extends AbstractMidasProposalProvider {
}
