/*
 * generated by Xtext 2.9.1
 */
package co.edu.javeriana.midas


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class MidasRuntimeModule extends AbstractMidasRuntimeModule {
}
