/*
 * generated by Xtext 2.12.0
 */
package co.edu.javeriana.midas.ide

import co.edu.javeriana.midas.MidasRuntimeModule
import co.edu.javeriana.midas.MidasStandaloneSetup
import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class MidasIdeSetup extends MidasStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new MidasRuntimeModule, new MidasIdeModule))
	}
	
}
